site_name: TF Utils Documentation
site_description: Documentation for TF Utils - A user-friendly tool for TFBern students
site_author: Oliver Seifert
repo_url: https://github.com/ImGajeed76/tfUtils
repo_name: ImGajeed76/tfUtils
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      title: On this page
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ImGajeed76/tfUtils
      name: TF Utils on GitHub
  generator: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - User Guide: user-guide.md
  - Development:
    - Getting Started: development/getting-started.md
    - Development Workflow: development/workflow.md
    - Project Structure: development/structure.md
    - Key Components: development/components.md
    - Creating Features: development/creating-features.md
  - License: license.md
