name: Python Application CI/CD

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  build-dev:
    needs: pre-commit
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build executable
        run: python build.py

      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        with:
          files: output/utils.exe
          prerelease: true
          name: "Development Build"
          tag_name: "dev-${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-build:
    needs: pre-commit
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build executable
        run: python build.py

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: output/utils.exe
          name: "Release ${{ github.ref_name }}"
          body: "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
